### ISSUE TITLE
Output filename selection

### ISSUE THREAD

**Issue by avchikar97** [avchikar97/Personalized-Earnings-Calendar-ICS#1]
Allow the user to choose the name of the output file
- Probably best to use the `-o` option to line up with other tools
- Default output filename can stay `next_earnings_calendar.ics`

**Comment by LoremIpsum42** [comment]
I opened a pull request for this feature.

**Comment by avchikar97** [comment]
Oh thanks! I just added a small comment, otherwise it looks good
